/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.OrderBLL;
import BLL.OrderDetailBLL;
import BLL.ProductBLL;
import Entity.Order;
import Entity.OrderDetail;
import Entity.Product;
import com.formdev.flatlaf.FlatLightLaf;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Clock
 */
public class addOrderDetailGUI extends javax.swing.JFrame {

    /**
     * Creates new form addOrderDetailGUI
     */
    private OrderDetailBLL odBll = new OrderDetailBLL();
    private ProductBLL proBll = new ProductBLL();

    public addOrderDetailGUI() {
        initComponents();
        comboxproduct();

    }

    public addOrderDetailGUI(int data) {
        initComponents();
        jTextFieldOID.setText(Integer.toString(data));
        comboxproduct();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldOID = new javax.swing.JTextField();
        jLabelOID = new javax.swing.JLabel();
        jLabelCID = new javax.swing.JLabel();
        jLabelDate = new javax.swing.JLabel();
        jLabelStatus = new javax.swing.JLabel();
        jTextFieldPrice = new javax.swing.JTextField();
        jButtonYes = new javax.swing.JButton();
        jButtonNo = new javax.swing.JButton();
        jLabelTitle = new javax.swing.JLabel();
        cbxProduct = new javax.swing.JComboBox<>();
        spnQuantity = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextFieldOID.setEditable(false);

        jLabelOID.setText("Order ID");

        jLabelCID.setText("Product ID");

        jLabelDate.setText("Quantity");

        jLabelStatus.setText("Price");

        jTextFieldPrice.setEditable(false);

        jButtonYes.setText("Yes");
        jButtonYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYes(evt);
            }
        });

        jButtonNo.setText("No");
        jButtonNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNo(evt);
            }
        });

        jLabelTitle.setFont(new java.awt.Font("Calibri Light", 1, 36)); // NOI18N
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("Add Order Detail");

        cbxProduct.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxProductItemStateChanged(evt);
            }
        });

        spnQuantity.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnQuantityStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabelCID)
                            .addGap(23, 23, 23))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabelDate)
                            .addGap(34, 34, 34))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabelStatus)
                            .addGap(53, 53, 53)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelOID)
                        .addGap(33, 33, 33)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldOID, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jTextFieldPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(cbxProduct, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spnQuantity))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonYes, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonNo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldOID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelOID))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCID)
                    .addComponent(cbxProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDate)
                    .addComponent(spnQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStatus)
                    .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNo)
                    .addComponent(jButtonYes))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnYes(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYes
        // TODO add your handling code here:
        String[] part = cbxProduct.getSelectedItem().toString().split("-");
        OrderDetail oDe = new OrderDetail();
        oDe.setOrderID(Integer.parseInt(jTextFieldOID.getText()));
        oDe.setProductID(Integer.parseInt(part[0]));
        Product p = proBll.getProduct(Integer.parseInt(part[0]));
        if (Integer.valueOf(spnQuantity.getValue().toString()) > p.getQuantity()) {
            spnQuantity.setValue(p.getQuantity());
            oDe.setQuantity(p.getQuantity());
            p.setQuantity(p.getQuantity()-Integer.valueOf(spnQuantity.getValue().toString()));
            proBll.updateProduct(p.getProductID(), p.getStrap(), p.getBrand(), p.getProductName(), p.getPrice(), p.getQuantity() , p.getProductDetail());
        } else {
            oDe.setQuantity(Integer.valueOf(spnQuantity.getValue().toString()));
        }
        oDe.setPrice(Float.parseFloat(jTextFieldPrice.getText()));

        odBll.addOrderDetail(oDe);

        OrderBLL oBll = new OrderBLL();
        Order ord = oBll.getOrder(oDe.getOrderID());

        int toquan = ord.getTotalQuantity();
        Float topri = ord.getTotalPrice();
        toquan = toquan + oDe.getQuantity();
        topri = topri + oDe.getPrice();

        ord.setTotalQuantity(toquan);
        ord.setTotalPrice(topri);
        oBll.updateOrder(ord);

        JOptionPane.showMessageDialog(this, "Complete to add OrderDetail", "Message",
                JOptionPane.INFORMATION_MESSAGE);
        this.setVisible(false);
        new OrderDetailGUI(oDe.getOrderID()).setVisible(true);
    }//GEN-LAST:event_btnYes

    private void btnNo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNo
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnNo

    private void spnQuantityStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnQuantityStateChanged
        // TODO add your handling code here:
        String[] part = cbxProduct.getSelectedItem().toString().split("-");
        Product p = proBll.getProduct(Integer.parseInt(part[0]));
        float sum = Integer.valueOf(spnQuantity.getValue().toString()) * p.getPrice();
        jTextFieldPrice.setText(String.valueOf(sum));
    }//GEN-LAST:event_spnQuantityStateChanged

    private void cbxProductItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxProductItemStateChanged
        // TODO add your handling code here:
        String[] part = cbxProduct.getSelectedItem().toString().split("-");
        Product p = proBll.getProduct(Integer.parseInt(part[0]));
        float sum = Integer.valueOf(spnQuantity.getValue().toString()) * p.getPrice();
        jTextFieldPrice.setText(String.valueOf(sum));
    }//GEN-LAST:event_cbxProductItemStateChanged

    private void comboxproduct() {
        List<Product> l = proBll.loadProduct();
        for (Product p : l) {
            cbxProduct.addItem(p.getProductID() + "-" + p.getProductName());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                addOrderDetailGUI addDetailGUI = new addOrderDetailGUI();
                addDetailGUI.setLocationRelativeTo(null);
                addDetailGUI.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxProduct;
    private javax.swing.JButton jButtonNo;
    private javax.swing.JButton jButtonYes;
    private javax.swing.JLabel jLabelCID;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelOID;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldOID;
    private javax.swing.JTextField jTextFieldPrice;
    private javax.swing.JSpinner spnQuantity;
    // End of variables declaration//GEN-END:variables
}
