/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BLL.CustomerBLL;
import Entity.Customer;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MSI VN
 */
public class CustomerGUI extends javax.swing.JFrame {

    private DefaultTableModel model;
    private CustomerBLL cusbll;
    private int id;

    public CustomerGUI() {
        initComponents();
        cusbll = new CustomerBLL();
        showTable();
    }

    public void showTable() {
        List listCate = cusbll.loadCustomer();
        Object[][] datamodel;
        datamodel = cusbll.convertCustomer(listCate);
        String[] title = { "CustomerId", "FullName", "Address" };
        DefaultTableModel model = new DefaultTableModel(datamodel, title);
        Customer_JTA.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BG_JPanell = new javax.swing.JPanel();
        Title_JLabel = new javax.swing.JLabel();
        BG_Detail = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Customer_JTA = new javax.swing.JTable();
        searchText = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        delButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Title_JLabel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 48)); // NOI18N
        Title_JLabel.setForeground(new java.awt.Color(102, 153, 255));
        Title_JLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title_JLabel.setText("Customer Management");

        BG_Detail.setBackground(new java.awt.Color(255, 255, 255));

        Customer_JTA.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null },
                        { null, null, null },
                        { null, null, null },
                        { null, null, null }
                },
                new String[] {
                        "CustomerID", "FullName", "Address"
                }) {
            boolean[] canEdit = new boolean[] {
                    false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        Customer_JTA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Customer_JTA);
        if (Customer_JTA.getColumnModel().getColumnCount() > 0) {
            Customer_JTA.getColumnModel().getColumn(0).setResizable(false);
            Customer_JTA.getColumnModel().getColumn(1).setResizable(false);
            Customer_JTA.getColumnModel().getColumn(2).setResizable(false);
        }

        searchText.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N

        searchButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch(evt);
            }
        });

        editButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdit(evt);
            }
        });

        addButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd(evt);
            }
        });

        delButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        delButton.setText("Del");
        delButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete(evt);
            }
        });

        refreshButton.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefresh(evt);
            }
        });

        javax.swing.GroupLayout BG_DetailLayout = new javax.swing.GroupLayout(BG_Detail);
        BG_Detail.setLayout(BG_DetailLayout);
        BG_DetailLayout.setHorizontalGroup(
                BG_DetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(BG_DetailLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(BG_DetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(BG_DetailLayout.createSequentialGroup()
                                                .addComponent(searchText, javax.swing.GroupLayout.PREFERRED_SIZE, 327,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(refreshButton)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(BG_DetailLayout.createSequentialGroup()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 811,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31,
                                                        Short.MAX_VALUE)
                                                .addGroup(BG_DetailLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(editButton,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 73,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(delButton, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(19, 19, 19)))));
        BG_DetailLayout.setVerticalGroup(
                BG_DetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(BG_DetailLayout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(editButton)
                                .addGap(48, 48, 48)
                                .addComponent(addButton)
                                .addGap(50, 50, 50)
                                .addComponent(delButton)
                                .addContainerGap(142, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BG_DetailLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(BG_DetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(searchText)
                                        .addComponent(refreshButton))
                                .addGap(27, 27, 27)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)));

        javax.swing.GroupLayout BG_JPanellLayout = new javax.swing.GroupLayout(BG_JPanell);
        BG_JPanell.setLayout(BG_JPanellLayout);
        BG_JPanellLayout.setHorizontalGroup(
                BG_JPanellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(BG_Detail, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BG_JPanellLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Title_JLabel)
                                .addGap(222, 222, 222)));
        BG_JPanellLayout.setVerticalGroup(
                BG_JPanellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(BG_JPanellLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(Title_JLabel)
                                .addGap(18, 18, 18)
                                .addComponent(BG_Detail, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(BG_JPanell, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(BG_JPanell, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdd(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAdd
        new addCustomerGUI().setVisible(true);
        this.dispose();
    }// GEN-LAST:event_btnAdd

    private void btnEdit(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEdit
        if (this.getId() == -1) {
            JOptionPane.showMessageDialog(this, "Vui long chon Customer muon sua thong tin!");
        } else {
            new editCustomerGUI(this.getId()).setVisible(true);
            this.dispose();
        }
    }// GEN-LAST:event_btnEdit

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_tblMouseClicked
        int i = Customer_JTA.getSelectedRow();
        this.setId(Integer.parseInt(Customer_JTA.getValueAt(i, 0).toString()));
    }// GEN-LAST:event_tblMouseClicked

    private void btnDelete(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDelete
        int result = JOptionPane.showConfirmDialog(this,
                "Ban co chac muon xoa Customer nay?",
                "Xac nhan",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (result == JOptionPane.YES_OPTION) {
            int err = 0;
            try {
                cusbll.delCustomer(id);
                loadAllCustomer();
            } catch (Exception e) {
                err = 1;
            }
            if (err == 0) {
                JOptionPane.showMessageDialog(this, "Xoa Customer thanh cong!");
            }
            if (err == 1) {
                JOptionPane.showMessageDialog(this, "Xoa Customer khong thanh cong!");
            }
        }
    }// GEN-LAST:event_btnDelete

    private void btnRefresh(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnRefresh
        loadAllCustomer();
        this.searchText.setText("");
        this.setId(-1);
    }// GEN-LAST:event_btnRefresh

    private void btnSearch(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSearch
        Customer cus = cusbll.getCustomer(this.getId());
        DefaultTableModel models = (DefaultTableModel) Customer_JTA.getModel();
        models.setRowCount(0);
        models.addRow(new Object[] {
                cus.getCustomerID(), cus.getFullName(), cus.getAddress()
        });
    }// GEN-LAST:event_btnSearch

    private void loadAllCustomer() {
        List cusList = cusbll.loadCustomer();
        Object[][] data = cusbll.convertCustomer(cusList);
        String[] title = { "CustomerID", "FullName", "Address" };
        DefaultTableModel model = new DefaultTableModel(data, title);
        Customer_JTA.setModel(model);
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BG_Detail;
    private javax.swing.JPanel BG_JPanell;
    private javax.swing.JTable Customer_JTA;
    private javax.swing.JLabel Title_JLabel;
    private javax.swing.JButton addButton;
    private javax.swing.JButton delButton;
    private javax.swing.JButton editButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchText;
    // End of variables declaration//GEN-END:variables
}
