/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BLL.BrandBLL;
import BLL.ProductBLL;
import BLL.StrapBLL;
import DAL.BrandDAL;
import DAL.ProductDAL;
import DAL.StrapDAL;
import Entity.Brand;
import Entity.Product;
import Entity.Strap;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zolo
 */
public class ProductGUI extends javax.swing.JFrame {

    /**
     * Creates new form ProductGUI
     */
    ProductDAL proDAL = new ProductDAL();
    ProductBLL proBLL = new ProductBLL();
    StrapBLL strbll = new StrapBLL();
    BrandBLL brbll = new BrandBLL();
    StrapDAL strdal = new StrapDAL();
    BrandDAL brdal = new BrandDAL();
    private static int id;
    private static int strID;

    public ProductGUI() {
        initComponents();
        loadAllproduct();
        comboxfindstap();
        comboxfindBrand();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        productTbl = new javax.swing.JTable();
        txtfindid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnadd = new javax.swing.JButton();
        btndel = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        cbfinstrap = new javax.swing.JComboBox<>();
        refreshBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        cbfinbrand = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        productTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Strap Type", "Brand", "Price", "Quantity", "Detail"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        productTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                productTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(productTbl);

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnadd.setText("Add");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btndel.setText("Del");
        btndel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelActionPerformed(evt);
            }
        });

        btnedit.setText("Edit");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });

        cbfinstrap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbfinstrapMouseClicked(evt);
            }
        });
        cbfinstrap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbfinstrapActionPerformed(evt);
            }
        });

        refreshBtn.setText("Refresh");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        jButton2.setText("Choose");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Choose");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        cbfinbrand.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbfinbrandMouseClicked(evt);
            }
        });
        cbfinbrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbfinbrandActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 887, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnadd)
                            .addComponent(btndel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnedit, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtfindid, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(refreshBtn)
                        .addGap(18, 18, 18)
                        .addComponent(cbfinstrap, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbfinbrand, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbfinbrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton3))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbfinstrap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(refreshBtn)
                                .addComponent(jButton2))))
                    .addComponent(txtfindid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(btnedit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnadd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btndel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        // TODO add your handling code her
        loadAllproduct();
        cbfinstrap.setSelectedItem("ALL");
        cbfinbrand.setSelectedItem("ALL");
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void productTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productTblMouseClicked
        // TODO add your handling code here:
        int i = productTbl.getSelectedRow();
        id = Integer.parseInt(productTbl.getValueAt(i, 0).toString());
//        System.out.println(cbbrand.getSelectedItem().);
    }//GEN-LAST:event_productTblMouseClicked

    private void btndelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelActionPerformed
        // TODO add your handling code here:
        proBLL.delProduct(id);
        loadAllproduct();
    }//GEN-LAST:event_btndelActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
        new editProductGUI(id).setVisible(true);
//       proBLL.updateProduct(Integer.parseInt(txtproductid.getText()),s,b,txtproductname.getText(),Integer.getInteger(txtprice.getText()),Integer.parseInt(txtquantity.getText()), txtDetail.getText());
    }//GEN-LAST:event_btneditActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        new addProductGUI().setVisible(true);
    }//GEN-LAST:event_btnaddActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Product pr = proDAL.getProduct(Integer.valueOf(txtfindid.getText()));
        DefaultTableModel model = (DefaultTableModel) productTbl.getModel();
        model.setRowCount(0);
        model.addRow(new Object[]{
            pr.getProductID(), pr.getProductName(), pr.getStrap().getStrapName(), pr.getBrand().getBrandName(), pr.getPrice(), pr.getQuantity(), pr.getProductDetail()
        });
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbfinstrapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbfinstrapMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_cbfinstrapMouseClicked

    private void cbfinstrapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbfinstrapActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cbfinstrapActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String temp = cbfinstrap.getSelectedItem().toString();
        if (temp.equals("ALL"))
            loadAllproduct();
        else {
            String[] temp1 = temp.split("-");
            int idfindstrap = Integer.valueOf(temp1[0].trim());
            findproduct(idfindstrap);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String temp = cbfinbrand.getSelectedItem().toString();
        if (temp.equals("ALL"))
            loadAllproduct();
        else {
            String[] temp1 = temp.split("-");
            int idfindbrand = Integer.valueOf(temp1[0].trim());
            findproductbybrand(idfindbrand);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cbfinbrandMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbfinbrandMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbfinbrandMouseClicked

    private void cbfinbrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbfinbrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbfinbrandActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductGUI().setVisible(true);
            }
        });
    }

    private void loadAllproduct() {
        List proList = proBLL.loadProduct();
        Object[][] data = proBLL.converProduct(proList);
        String[] title = {"Product ID", "Product Name", "Srtap Type", "Brand", "Price", "Quantity", "Detail"};
        DefaultTableModel model = new DefaultTableModel(data, title);
        productTbl.setModel(model);
    }

    private void findproduct(int idstr) {
        List proList = proBLL.loadProductbyStrap(idstr);
        Object[][] data = proBLL.converProduct(proList);
        String[] title = {"Product ID", "Product Name", "Srtap Type", "Brand", "Price", "Quantity", "Detail"};
        DefaultTableModel model = new DefaultTableModel(data, title);
        productTbl.setModel(model);
    }
    private void findproductbybrand(int idbr) {
        List proList = proBLL.loadProductbyBrand(idbr);
        Object[][] data = proBLL.converProduct(proList);
        String[] title = {"Product ID", "Product Name", "Srtap Type", "Brand", "Price", "Quantity", "Detail"};
        DefaultTableModel model = new DefaultTableModel(data, title);
        productTbl.setModel(model);
    }

    private void comboxfindBrand() {
        cbfinbrand.addItem("ALL");
        cbfinstrap.setSelectedItem("ALL");
       List<Brand> l = brbll.loadBrand();
        for (Brand b : l) {
            cbfinbrand.addItem(b.getBrandID() + " - " + b.getBrandName());
        }
    }
    
    private void comboxfindstap() {
        cbfinstrap.addItem("ALL");
        cbfinstrap.setSelectedItem("ALL");
        List<Strap> l = strbll.loadStrap();
        for (Strap s : l) {
            cbfinstrap.addItem(s.getStrapID() + " - " + s.getStrapName());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btndel;
    private javax.swing.JButton btnedit;
    private javax.swing.JComboBox<String> cbfinbrand;
    private javax.swing.JComboBox<String> cbfinstrap;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable productTbl;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JTextField txtfindid;
    // End of variables declaration//GEN-END:variables
}
